#!/bin/bash

local i=0
red=`tput setaf 1`
 white=`tput setaf 7`

echo -n "make re" | make re
echo -n "reset" | reset

echo -n "Setenv and Unsetenv: " ; echo -e "unsetenv abc \n setenv abc lol \n setenv toto \n setenv tyty toto \n unsetenv toto tyty \n setenv abc moomoo \n setenv a moomoo\n setenv b Jairesisteauko \n setenv abc Jairesisteauko\n setenv" |./mysh | grep -i abc=Jairesisteauko >/dev/null ;
if [ $? -eq 0 ] ;
         then echo ">OK" &i=$((i+1));
         else echo  "${red}KO${white}";
fi

echo ; echo -n "Simple exec: " ; echo -e "mkdir toto \n ls -l " |./mysh | grep -i toto >/dev/null ;
if [ $? -eq 0 ];
          then echo ">OK"  &i=$((i+1));
          else echo  "${red}KO${white}";
fi
echo -e "rm -rf toto" | rm -rf toto

echo -e "mkdir toto \n ../bin/ls -l " |./mysh | grep -i toto >/dev/null ;
if [ $? -eq 0 ] ;
         then echo  "${red}KO${white}";
         else echo ">OK"  &i=$((i+1));
fi
echo -e "rm -rf toto" | rm -rf toto

 echo -e "mkdir toto \n cd toto \n mkdir cd \n ls -la" |./mysh | grep -i cd >/dev/null;
  if [ $? -eq 0 ] ;
           then echo ">OK" &i=$((i+1));
	            else echo  "${red}KO${white}";
		     fi
		      echo -e "rm -rf toto" | rm -rf toto

 echo -n "exit: " ; echo -e "exit 23" |./mysh ; echo "$?" | grep -i 23 >/dev/null ;
  if [ $? -eq 0 ] ;
           then echo ">OK" &i=$((i+1));
	            else echo  "${red}KO${white}";
		     fi

 echo -e "exit 100" |./mysh ; echo "$?" | grep -i 100 >/dev/null ;
  if [ $? -eq 0 ] ;
           then echo ">OK" &i=$((i+1));
	            else echo  "${red}KO${white}";
		     fi
		      echo -e "exit" |./mysh ; echo "$?" | grep -i 0 >/dev/null ;
		       if [ $? -eq 0 ] ;
		                then echo ">OK" &i=$((i+1));
				         else echo  "${red}KO${white}";
					  fi
					   echo -e "exit 50" |./mysh ; echo "$?" | grep -i 50 >/dev/null ;
					    if [ $? -eq 0 ] ;
					             then echo ">OK" &i=$((i+1));
						              else echo  "${red}KO${white}";
							       fi

 echo -n "cd: " ; echo -e "cd \n cd -\n cd \n cd /home/ \n cd / \n cd - \n cd .. \n cd bin\n ls " |./mysh | grep -i ls >/dev/null ;
  if [ $? -eq 0 ] ;
           then echo ">OK" &i=$((i+1));
	            else echo  "${red}KO${white}";
		     fi

 echo -n "Setenv and Unsetenv: " ; echo -e "unsetenv abc \n setenv abc lol \n setenv toto \n setenv tyty toto \n unsetenv toto tyty \n setenv abc moomoo \n env" |./mysh | grep -i abc=moomoo >/dev/null ;
  if [ $? -eq 0 ] ;
           then echo ">OK" &i=$((i+1));
	            else echo  "${red}KO${white}";
		     fi
		      echo -e "unsetenv abc \n setenv abc lol \n setenv toto \n setenv tyty toto \n unsetenv toto tyty \n setenv abc moomoo \n setenv a moomoo\n setenv b Jairesisteauko \n setenv abc Jairesisteauko\n setenv" |./mysh | grep -i abc=Jairesisteauko >/dev/null ;
		       if [ $? -eq 0 ] ;
		                then echo ">OK" &i=$((i+1));
				         else echo  "${red}KO${white}";
					  fi
					   echo -e "setenv PATHS /bin \n unsetenv PATH \n setenv PATH /bin: \n setenv" |./mysh | grep -i PATH=/bin: >/dev/null ;
					    if [ $? -eq 0 ] ;
					             then echo ">OK" &i=$((i+1));
						              else echo  "${red}KO${white}";
							       fi
							        echo -e " setenv P \n setenv PAT \n setenv PATHS \n unsetenv \n unsetenv PATH \n mkdir toto\n ls" |./mysh 2>&1 | grep -i toto >/dev/null ;
								 if [ $? -eq 0 ] ;
								          then echo  "${red}KO${white}";
									           else echo ">OK" &i=$((i+1));
										    fi
										     echo -e "rm -rf toto" | rm -rf toto

 echo -n "Segault : " ; echo "int main;" > /tmp/test$$.c ; gcc -o /tmp/test$$ /tmp/test$$.c 2>/dev/null ; echo "/tmp/test$$" | ./mysh 2>&1 | grep -i Segmentation >/dev/null ;
  if [ $? -eq 0 ] ;
           then echo ">OK" &i=$((i+1));
	            else echo  "${red}KO${white}";
		     fi

 echo -n "Floating : " ; echo "int main() {int a=3; a=a/0;}" > /tmp/test$$.c ; gcc -o /tmp/test$$ /tmp/test$$.c 2>/dev/null ; echo "/tmp/test$$" | ./mysh 2>&1 | grep -i floating >/dev/null ;
  if [ $? -eq 0 ] ;
           then echo ">OK" &i=$((i+1));
	            else echo  "${red}KO${white}";
		     fi

 echo -n "Path exec : "
  echo -e "mkdir toto \n /ls \n" |./mysh | grep -i toto >/dev/null ;
   if [ $? -eq 0 ] ;
            then echo  "${red}KO${white}";
	             else echo ">OK" &i=$((i+1));
		      fi
		       echo -e "cd /bin/ \n ./ls \n" |./mysh | grep -i ls >/dev/null ;
		        if [ $? -eq 0 ] ;
			         then echo ">OK" &i=$((i+1));
				          else echo  "${red}KO${white}";
					   fi
					    echo -e "cd /bin/ \n ls \n" |./mysh | grep -i ls >/dev/null ;
					     if [ $? -eq 0 ] ;
					              then echo ">OK" &i=$((i+1));
						               else echo  "${red}KO${white}";
							        fi
								 echo -e "cp /bin/ls my_ls \n ./my_ls \n " |./mysh | grep -i my_ls >/dev/null ;
								  if [ $? -eq 0 ] ;
								           then echo ">OK" &i=$((i+1));
									            else echo  "${red}KO${white}";
										     fi
										      echo -e "rm -rf my_ls" | rm -rf my_ls
										       echo -e "rm -rf toto" | rm -rf toto

 echo -e "cd / \n cd /bin \n ./ls" |./mysh | grep -i ls >/dev/null ;
  if [ $? -eq 0 ] ;
           then echo ">OK" &i=$((i+1));
	            else echo  "${red}KO${white}";
		     fi
		      echo -e "rm -rf my_ls" | rm -rf my_ls
		       echo -e "rm -rf toto" | rm -rf toto
		        echo "                        Mark :" $i "/20" ; echo
echo "					Made by leroy_0 and klein_h"; echo
